name: myselff_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  intl: ^0.19.0
  flutter_modular: ^5.0.3
  flutter_animate: ^4.2.0+1
  flutter_mobx: ^2.0.6
  sqflite: ^2.3.0
  path:
  mobx: 2.2.0
  dio: 5.3.0
  google_fonts: ^6.1.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: 2.3.0
  build_runner: 2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
